# Generated by Django 4.0.3 on 2022-03-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='imagens',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='imagen1',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='imagen2',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='imagen3',
            field=models.ImageField(default=11, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='imagen4',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='imagen5',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
