# Generated by Django 4.0.3 on 2022-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_remove_veiculo_imagens_veiculo_imagen1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='imagen5',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='imagens',
            field=models.ManyToManyField(to='plataforma.imagem'),
        ),
    ]
