# Generated by Django 4.0.3 on 2022-03-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_imagem_remove_veiculo_imagen1_remove_veiculo_imagen2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='kmRodados',
            field=models.IntegerField(max_length=30),
        ),
    ]
