# Generated by Django 4.0.3 on 2022-03-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0004_alter_veiculo_kmrodados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='baiiro',
            new_name='bairro',
        ),
    ]
