# Generated by Django 4.0.3 on 2022-03-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_rename_baiiro_veiculo_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='kmRodados',
            field=models.IntegerField(),
        ),
    ]
