# Generated by Django 4.0.3 on 2022-03-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0008_delete_cidade_remove_veiculo_imagens_veiculo_imagem1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='imagem1',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='imagem2',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='imagem3',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
