# Generated by Django 4.0.3 on 2022-03-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_alter_veiculo_imagem1_alter_veiculo_imagem2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='imagem2',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='imagem3',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='imagem1',
            field=models.FileField(upload_to='img'),
        ),
    ]
