# Generated by Django 4.0.3 on 2022-03-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_remove_veiculo_imagem2_remove_veiculo_imagem3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='imagem2',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='imagem3',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
