# Generated by Django 4.0.3 on 2022-03-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0013_contato_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='telefone',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
